version: 0.6.2

namespace: datewithmark
project: datewithmark

services:
  - name: web
    image: ghcr.io/markmorcos/datewithmark
    port: 80
    ingress:
      host: datewithmark.com
      path: /
      pathType: Prefix
